### PR TITLE
Request to merge Create-db branch into dev

### PR DESCRIPTION
**Pull request by flemton**
Dear reviewer, in this PR my partner (@federicaulzurrun) and I (@flemton ) did the following

- Created a file named schema_based_on_diagram.sql
- Implemented the database from the diagram below
Screenshot 2023-06-21 at 6 18 16 AM

- [Joined tables from many-to-many relationships](https://github.com/flemton/clinic-database/commit/507c11c1970abdc105982607f19753b48044f480)
- [Added FK indexes](https://github.com/flemton/clinic-database/commit/68c01a8b7a6a5986495b8cd8312f225d8fdc5b7f)
__Any suggested changes are highly welcome and will be treated with the utmost attention, cheers 🥂__

### CODE REVIEW

**Comment by binhussen** [comment]
@flemton and @federicaulzurrun would you fix `mit` broken link and remove the `note` bellow the mit

**Comment by flemton** [comment]
Yes sir, on it

**Comment by binhussen** [comment]
@flemton your mit link is broken because of you don't have `LICENSE.md`

**Review by binhussen — APPROVED** [review]
Hi @flemton and @federicaulzurrun , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉

## Highlights
- Created Bsedon diagram ✔️
- Well Structured Query ✔️
- Used Git flow ✔️
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
